Update codebase to python 3.7
yashaka/selene pull request #316
Opened 2021-04-12 10:31 UTC by initial1ze

Let me know if there is an issue or something needs to be improved.
Thank you.

2021-04-13 15:56 UTC, aleksandr-kotlyar commented on selene/support/shared/config.py
> +    def window_height(self, value: int | None):
This is a python 3.10 feature https://www.python.org/dev/peps/pep-0604 
It shouldn't be here. The task is to up to 3.7 python, not 3.10.

2021-04-13 16:03 UTC, aleksandr-kotlyar commented on selene/core/condition.py
> +            errors: list[Exception] = []
It's not python 3.7 - it's python 3.9 feature https://www.python.org/dev/peps/pep-0585/
It shouldn't be here for now.

2021-04-13 16:19 UTC, aleksandr-kotlyar requested changes
@initial1ze thank you for your time to make this PR.
You need to rollback some changes from 3.10 and 3.9 python before we could approve your PR.

2021-04-13 16:36 UTC, initial1ze commented
Sorry for the trouble, i will make the required changes.

2021-09-11 08:43 UTC, aleksandr-kotlyar commented
That was an attempt to resolve #288

2021-09-11 08:44 UTC, closed without merging