Improved tests structure in files
yashaka/selene pull request #355
Opened 2021-06-17 16:32 UTC by Elena7788

Improved tests' structure in **element__element__lazy_search_test.py** and **element__lazy_search_test.py**

2021-06-19 15:48 UTC, yashaka requested changes
please refactor according to comments;)

2021-06-19 15:48 UTC, yashaka commented on tests/integration/element__element__lazy_search_test.py
> +        /p>
should be
```
</p>
```

2021-06-19 15:48 UTC, yashaka commented on tests/integration/element__lazy_search_test.py
>      assert element().is_displayed() is True
should be brokent into ACT + ASSERT with additional variable with answer

2021-06-19 15:48 UTC, yashaka commented on tests/integration/element__lazy_search_test.py
>      page = GivenPage(session_browser.driver)
same logic should be applied as in video mentioned earlier

2021-06-19 15:48 UTC, yashaka commented on tests/integration/element__lazy_search_test.py
> +        *</h1>
should be broken with a common sense, not just at some point...

good version is more like this:
```
<h1 id="will-be-existing-element-id" style="display:none">
    Hello kitty:*
</h1>
```

2021-06-19 15:48 UTC, yashaka commented on tests/integration/element__lazy_search_test.py
>      assert element().is_displayed() is False
same as in first file...

2026-05-11 13:37 UTC, aleksandr-kotlyar commented
Closing in favor of #645

2026-05-11 13:37 UTC, closed without merging